import type { Metadata } from 'next'
import '../styles/globals.css'
import { FontWrapper } from '@/common/wrappers'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="es">
      <FontWrapper>{children}</FontWrapper>
    </html>
  )
}
